export const CATEGORY = {
	ALL: 0,
	GIOI_THIEU_CLB: 1,
	CHUYEN_DONG_YES: 2,
	TAI_LIEU_LOAI_1: 3,
	PROFILE_THANH_VIEN: 4,
	CUOC_THI_THUONG_NIEN: 5,
	AN_PHAM_BAO: 6,
	NHA_TAI_TRO: 7,
	TAI_LIEU_LOAI_2: 8,
}